### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished after connected? is true

### ISSUE THREAD

**Issue by boskowski** [pierrickrouxel/activerecord-jdbcas400-adapter#3]
I'm struggling with a native connection to an OS400 machine using the adapter. 

If I try to use AR, I get a ConnectionNotEstablished error as soon as I try to use an (apparently) established connection. If I connect to DB2 directly using DriverManager, it works.

Please have a look at this [this](https://gist.github.com/boskowski/92d6803e2c152e1fdece) transcript.

Thank you very much for helping me!

**Comment by pierrickrouxel** [comment]
I haven't IBM i to try your transcript today but I think you can't perform query because you should checkout connection before use it.

Try without connection pool : 

`ˋ`ruby
connection = ActiveRecord::Base.connection
ˋ`ˋ

**Comment by boskowski** [comment]
I managed to solve this by adding connection parameter :url=>"jdbc:as400://". Thank you!

**Comment by pierrickrouxel** [comment]
I will do some tests. It's should work without that.
